### ISSUE TITLE
when updating to 2.4, default rtcpmode has to be changed to `average`

### ISSUE THREAD

**Issue by jchang0419** [voxeet/voxeet-uxkit-react#10]
**Describe the bug**

when using uxkit, the default is set to worst. in 2.4+, the default is now "average". The best approach would be to pass in nothing, and let the sdk decide if the developer does not choose a mode.

**Minimalistic code (recommended)**

https://github.com/voxeet/voxeet-uxkit-react/blob/master/src/app/components/ConferenceRoom.js#L488

**Comment by Energizz** [comment]
`rtcpmode` has been removed from the UXKit props, will be deployed in the next release
