### ISSUE TITLE
Installation problem - 404 error '@voxeet/media-engine@0.16.0' is not in the npm registry

### ISSUE THREAD

**Issue by narasimhancloudix** [voxeet/voxeet-uxkit-react#100]
**Describe the bug**

npm install gives 404 error for media-engine node_module

**Expected Behaviour**

npm install succeeds without any error

**Steps to Reproduce the Problem**

  1. Download the repo as zip file
  2. Run the command - npm i @voxeet/voxeet-web-sdk @voxeet/react-components @voxeet/react-redux-5.1.1@5.1.1 --save
  3. Below error is shown

npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @voxeet/media-engine@undefined
npm WARN node_modules/@voxeet/media-engine
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @voxeet/media-engine@"0.16.0" from @voxeet/voxeet-web-sdk@2.3.0
npm WARN node_modules/@voxeet/voxeet-web-sdk
npm WARN   peer @voxeet/voxeet-web-sdk@"2.3.0" from the root project
npm WARN   1 more (@voxeet/react-components)
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@voxeet%2fmedia-engine - Not found
npm ERR! 404
npm ERR! 404  '@voxeet/media-engine@0.16.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-02-26T06_54_04_852Z-debug.log

**Comment by FabienLavocat** [comment]
Please upgrade to the latest version of the [sdk](https://www.npmjs.com/package/@voxeet/voxeet-web-sdk/v/3.1.1):
```
@voxeet/voxeet-web-sdk@3.1.1
```

**Comment by wg-daniel** [comment]
@FabienLavocat Perhaps it's best to re-open this. `@voxeet/react-components` itself is still expecting `v2.3.0` to be installed. 

Force install gets the job done, but it would be better to update the expected dependency.

**Comment by FabienLavocat** [comment]
@wg-daniel I created an internal ticket to have the team fixing the dependency version. Thanks!

**Comment by FabienLavocat** [comment]
Will be fixed with #107
