### ISSUE TITLE
3.1.0 release breaks example in docs -- crashes after starting a conference

### ISSUE THREAD

**Issue by ajsharp** [voxeet/voxeet-uxkit-react#104]
**Describe the bug**

The example listed [here](https://dolby.io/developers/interactivity-apis/reference/client-ux-kit/uxkit-voxeet-react) crashes when you click the Join Room button.

**Expected Behaviour**

[Describe the expected behaviour of the feature.]

**Steps to Reproduce the Problem**

  1. Run the example from the docs site
  2. Click "Join Room"
  3. 💥

**Specifications**

  - Device: Web chrome
  - OS: macOS 10.15.7
  - Platform: Web / chrome
  - Version:
    - @voxeet/react-components 3.1.0

**Comment by ajsharp** [comment]
Fixed by #103

**Comment by codal-sbelim** [comment]
any update on this bug?

**Comment by FabienLavocat** [comment]
Hi @ajsharp @codal-sbelim I opened an internal ticket to get your pull request reviewed and merged.
Thank you for reporting it!

**Comment by Energizz** [comment]
Modifications has been integrate inside our developement to run more tests and it will be release in the next version which will be deployed soon. 
Thanks you for your report and your modification !

**Comment by youssmak** [comment]
> which will be deployed soon.

Hi @Energizz, any news on this ?
