### ISSUE TITLE
Leave conference but the VoxeetSDK.session.participant not clean

### ISSUE THREAD

**Issue by almorak** [voxeet/voxeet-uxkit-react#11]
**I cloned the master project for customizing the UI & socket implementation for the chat function.
But when I end the conference, redirect to other customize page, and navigate to ConferenceRoom Again.
The timer showing 2 time, one is the time ended, another is the new one.
In /src/app/action/ConferenceActions.js.** 

static initialize(consumerKey, consumerSecret) {
    return (dispatch) => {
      return this._initializeListeners(dispatch)
        .then(() => {
          **console.log('initialize:',VoxeetSDK.session.participant,'|',VoxeetSDK) < ----- added this log**
          VoxeetSDK.session.participant ||
            VoxeetSDK.initialize(consumerKey, consumerSecret).catch((err) => {
              this._throwErrorModal(err);
            });

        })
        .then((userId) => {
          dispatch(this._sdkInitializedSuccessful(userId));
        })
        .catch((err) => {
          dispatch(ErrorActions.onError(err));
        });
    };
  }

**First time VoxeetSDK.session.participant is undifined, 
Second time it show:**
{ id: "f1b20cb0-1f8e-3170-8428-8405468ec9fc"
info: {name: "XXXXXX", externalId: "", avatarUrl: undefined, sdkVersion: "2.3.1"}
status: "Connected"
streams: []
_events: {}
_eventsCount: 0
_maxListeners: undefined
}

**then i added a log to :** 

static leave() {
    return (dispatch, getState) => {
      const {
        voxeet: { controls },
      } = getState();
      return VoxeetSDK.conference.leave().then(() => {
        dispatch(TimerActions.stopTime());
        dispatch(ConferenceActions._conferenceLeave());
        dispatch(ConferenceActions._conferenceLeave(controls.disableSounds));
        if (controls.closeSessionAtHangUp) {
          this._removeListeners().then(() => {
            **console.log('VoxeetSDK.session.close') <-----------added this line, but no log in console**
            VoxeetSDK.session.close();
          });
        }
      });
    };
  }

**but it never fires the log, please note that controls.closeSessionAtHangUp == true**

**I have checked the session storage in chrome but doesn't exist.**
**Please advise how to clean the session.**

**Comment by Energizz** [comment]
Hello @almorak sorry for the delay of response, do you still experience issue ? If yes, feel free to reach out our support team https://support.dolby.io/

Have a great day,
