### ISSUE TITLE
Could not play the sound Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by UJWALGUPTA** [voxeet/voxeet-uxkit-react#114]
**Describe the bug**

Getting this error while using voxeet web sdk. 
**Expected Behaviour**

Should have launched the live conference.

**Specifications**

  - Device: [e.g. Desktop]
  - OS: [e.g.  windows]
  - Version:
    - _for each libraries : name -> version_
    - [e.g. @voxeet/voxeet-web-sdk 3.1.1 & 3.1.2]
    - [e.g. @voxeet/react-components 3.1.0]

**Comment by FabienLavocat** [comment]
Could you please provide some logs from the console to understand where the problem happens.
Also, I transferred your issue to the [voxeet-uxkit-react](https://github.com/voxeet/voxeet-uxkit-react) because it is related to the UXKit not the client SDK.

**Comment by UJWALGUPTA** [comment]
Hey Fabien, Ujwal this side from talkie.
We already had our talk on Dolby support if you remember. You had also sent some code snippets there.

**Comment by FabienLavocat** [comment]
Hey Ujwal! Yes :)
In order to get the music files to play, you need to import the music files in your project -> https://github.com/voxeet/voxeet-uxkit-react/tree/master/src/static/sounds
Then, in the `webpack.config.js`, you can import the plugin:
```javascript
const CopyPlugin = require("copy-webpack-plugin");
```
Then, add the rule:
```javascript
{
    test: /\.mp3$/,
    loader: "file-loader",
    options: {
        name: "sounds/[name].[ext]",
    }
},
```
Then, use the plugin to copy the sound files from your static folder:
```javascript
new CopyPlugin({
    patterns: [
        { from: "./web/static" }
    ],
}),
```

**Comment by FabienLavocat** [comment]
If you are still facing this issue, please reopen.
