### ISSUE TITLE
Compatible with react@17.0.2?

### ISSUE THREAD

**Issue by emorling** [voxeet/voxeet-uxkit-react#117]
I tried to install this is in an existing project, but it does not seem to work with react@17.0.2?

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0-0" from @voxeet/react-redux-5.1.1@5.1.1
npm ERR! node_modules/@voxeet/react-redux-5.1.1
npm ERR!   @voxeet/react-redux-5.1.1@"5.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by FabienLavocat** [comment]
Hi @emorling,
The package `@voxeet/react-redux-5.1.1` is not compatible with react@17.0.2, only 15 and 16.

**Comment by emorling** [comment]
I understand, are there any plans to remedy that going forward? To make it future proof?

**Comment by FabienLavocat** [comment]
@emorling I've requested someone to look at it internally, I'll keep you updated on this request. Thanks!

**Comment by emorling** [comment]
Thank you, much appreciated!

**Comment by FabienLavocat** [comment]
The `develop` branch is being updated for React 17 and a compatible version of Redux in #127

**Comment by FabienLavocat** [comment]
We released today the latest version of the UXKit that uses React 17.
