### ISSUE TITLE
customLocalizedStrings documentation is incorrect

### ISSUE THREAD

**Issue by anotherstarburst** [voxeet/voxeet-uxkit-react#153]
**Describe the bug**

The documentation for `customLocalizedStrings` is not correct on two counts.

> ...Use an array prefixed with the correct language key. (en, fr, it, ...)

1. Arrays cannot be prefixed. So the example code:

```
[en: {
    noPstnNumbers: "There is no PSTN numbers...",
    electronloading: "Voxeet is loading, please wait",
...
```

doesn't work. I assume this should be an object e.g. 

```
{en: {
    noPstnNumbers: "There is no PSTN numbers...",
    electronloading: "Voxeet is loading, please wait",
...
```
as this is the case in the code itself https://github.com/voxeet/voxeet-uxkit-react/blob/e19918aaccd2a1075e90b5b222d7e4064f1a1e36/src/app/languages/localizedStrings.js

**Comment by FabienLavocat** [comment]
Absolutely, the documentation was wrong, it has been removed from the README in `develop`.
Thanks you,
Fabien
