### ISSUE TITLE
Pollution of readme with redundant release information

### ISSUE THREAD

**Issue by jensenbox** [voxeet/voxeet-uxkit-react#160]
**Describe the bug**

Unable to read the readme due to overload of release notes that are duplicated in the release section of github.

**Expected Behaviour**

A nice clean readme to allow for a developer to get started faster.

**Steps to Reproduce the Problem**

  1. Go to repository in Github
  2. Try to read the relevant content of the readme

**Comment by FabienLavocat** [comment]
The changes are available in the `develop` branch.
