### ISSUE TITLE
Hide Sidebar which shows the list of Users in conference

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#203]
Is there a way to hide the sidebar which shows list of user in an conference?

![image](https://user-images.githubusercontent.com/98312418/162188627-888aa057-f3da-4037-a351-b57f14b057dd.png)

I can do it via css by setting .SidebarList as display none, but I want to hide/unhide it dynamically using some property is it possible?

Thanks

**Comment by FabienLavocat** [comment]
Thank you for your questions @edotappstore, we do not have a programatic way to toggle the attendee list, BUT, if you build your app directly using the source code of this UXKit, then you can trigger the toggle the attendees list - https://github.com/voxeet/voxeet-uxkit-react/blob/master/src/app/actions/ControlsActions.js#L253

**Comment by edotappstore** [comment]
Thank you @FabienLavocat 
i handled it via css display property.

**Comment by FabienLavocat** [comment]
You can share PPT and PPTX as well as PDF documents. Right now, it looks like the file selection filters down to only PDF files (I will send an update) but you can still select a PowerPoint document.

**Comment by edotappstore** [comment]
Thank you @FabienLavocat
