### ISSUE TITLE
Dolby io not loading in latest version of @voxeet package

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#208]
Greeting the below error and Dolby io screen not loading 

![VOXITdolbyioError](https://user-images.githubusercontent.com/98312418/163321050-25ccdd16-bc34-44ea-bf5e-853ee960abe8.png)

**Package version on which error is occurring**
"@voxeet/react-components": "^3.2.4",
"@voxeet/react-redux-5.1.1": "^5.1.1",
 "@voxeet/voxeet-web-sdk": "^3.0.3" 

**Works fine when i downgraded to** 

"@voxeet/react-components": "^3.0.0",
"@voxeet/react-redux-5.1.1": "^5.1.1",
"@voxeet/voxeet-web-sdk": "^3.0.0",

**Comment by FabienLavocat** [comment]
Can you upgrade to the latest version of the SDK:
```
"@voxeet/voxeet-web-sdk": "^3.4.1"
```

**Comment by edotappstore** [comment]
@FabienLavocat  ok ill upgrade the sdk and check

**Comment by edotappstore** [comment]
@FabienLavocat its working now with the sdk update thank you
