### ISSUE TITLE
Any provision to get the current selected slide in file sharing feature?

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#209]
Hi

Can we get the selected slide position or current slide file url?
Is there any provision for this via this plugin?

I want to provide provision to download the current slide
 
![image](https://user-images.githubusercontent.com/98312418/163366578-0a8980ce-587a-40a3-9dac-85b7b5503e6d.png)

**Comment by FabienLavocat** [comment]
If you customize this library, you can access the slide using the code `VoxeetSDK.filePresentation.current` and get the current position as well as the number of slides in the presentation.
To get the URL of a specific slide, you can use the following:
```javascript
await VoxeetSDK.filePresentation.image(position);
```

**Comment by edotappstore** [comment]
> If you customize this library, you can access the slide using the code `VoxeetSDK.filePresentation.current` and get the current position as well as the number of slides in the presentation. To get the URL of a specific slide, you can use the following:
> 
> ```js
> await VoxeetSDK.filePresentation.image(position);
> ```
Thank you for the reply
can we download the image from that url which we get using await VoxeetSDK.filePresentation.image(position)?

**Comment by FabienLavocat** [comment]
Absolutely, you can download the image using the URL provided by this function.

**Comment by edotappstore** [comment]
Thank you @FabienLavocat
