### ISSUE TITLE
Listener cant view shared file if audio and video constraints are set to false

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#214]
In the below image by default audio is set to true and video to be false, I am facing issue with the Dolby io file sharing  If i set both to false since i want a conference without any audio and video.
 
![image](https://user-images.githubusercontent.com/98312418/165218022-6c616f39-e073-4f2e-b739-f83af021e124.png)

**Expected Behaviour**
User having admin rights to share file and all the listener should able to connect to conference without audio and video and must be able to view the shared file

**Steps to Reproduce the Problem**

  1. Set the constraint  as `constraints: {
        audio: false,
        video: false,
      },`
  2. Start the conference and share a file.
  3. join the conference as a listener (will see a blank dolby io conference as shown in the image below)

1) User with admin rights to share file `isAdmin:true`

![image](https://user-images.githubusercontent.com/98312418/165219915-a625a950-267f-46c8-8b5a-b39d10255c07.png)

2) Listener who should view the shared file but getting blank screen `isListener:true`
![image](https://user-images.githubusercontent.com/98312418/165220027-8c9f63ce-b839-4a01-89cc-40ce3cc1bda8.png)

**Specifications**
  - OS: Windows
  - Version:
   "@voxeet/react-components": "^3.2.4",
    "@voxeet/react-redux-5.1.1": "^5.1.1",
    "@voxeet/voxeet-web-sdk": "^3.4.1",

**Note**
1) Both the user are on same conference.
2) File sharing works if Audio is set to true.

**Comment by FabienLavocat** [comment]
Thank you for this report. It looks like the problem is due to the fact when you are part of a conference with no audio and no video, we consider that user being `INACTIVE` and it looks like something in the code of this UXKit prevents from displaying the slides coming from an inactive user.
As as workaround, you can join with `audio: true` but mute yourself.

I'll keep looking into where the issue is located.

Thanks,
Fabien

**Comment by edotappstore** [comment]
Thank you @FabienLavocat 
For now ill use the workaround provided.

I hope this issue will be addressed sooner.

**Comment by edotappstore** [comment]
@FabienLavocat  is this fix pushed on to the latest version of @voxeet/voxeet-web-sdk?

**Comment by FabienLavocat** [comment]
@edotappstore the fix is not in the `master` branch so it has not been published as a new version of `@voxeet/react-components`. I would recommend for you to get the source code of the `develop` branch if this is a critical issue that you need to be fixed asap.

**Comment by edotappstore** [comment]
@FabienLavocat  any plans to publish this fix as a new version?

**Comment by FabienLavocat** [comment]
@edotappstore we are going to cherry pick some of the commits from the `develop` branch and merge them into master. The amount of work that is pending is too important to merge it all into master, this would create conflicts with most of the users of the library (React 17, Redux...). I will keep you posted once I have an update on the delivery.
I would recommend for you to directly import the code of the `develop` branch into your application if this is time sensitive.

**Comment by edotappstore** [comment]
@FabienLavocat i took the latest version of the develop branch, so i was trying to publish this develop branch code to npm and then import this in my application.
Is this the right way to do?

If yes then i am getting the following error 
![image](https://user-images.githubusercontent.com/98312418/170261124-bd8e27ab-7fdf-4e3a-8400-678e247da7b2.png)

can you please have a look and let me know where m going wrong?
