### ISSUE TITLE
Images from the UXKit are not loading

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#224]
**Icons on DolbyIo UI are not loading **
**1. All images for button have broken image**

![image](https://user-images.githubusercontent.com/98312418/173282809-fa16ccde-7c5c-40b7-a371-13a022dd4026.png)

**Steps to Reproduce the Problem**

  1. Update to latest version of @voxeet/react-components 3.0.0 and @voxeet/voxeet-web-sdk to 3.5.1
  2. Load the DolbyIo component
  3. Dolby IO screen will load with broken icons

**Specifications**
On Windows machine

**Comment by FabienLavocat** [comment]
The version [3.3.3](https://github.com/voxeet/voxeet-uxkit-react/releases/tag/3.3.0) of the UXKit was released 4 days ago, please upgrade to that version. It is also using React 17 now, so make sure your application works as expected with this version.
Checkout this sample application - https://github.com/dolbyio-samples/comms-conference-app - to make sure you are following the same steps for the migration.

**Comment by edotappstore** [comment]
@FabienLavocat  i made a mistake while typing the  @voxeet/react-components version 
issue m getting in version 3.3.0 and not 3.0.0
Same issue i had found in your dev branch #216

**Comment by FabienLavocat** [comment]
Please give a try to the version [3.3.3](https://github.com/voxeet/voxeet-uxkit-react/releases/tag/3.3.0) of the UXKit.
