### ISSUE TITLE
Selected ppt file not getting converted properly 

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#225]
Hi there,

When i select a ppt file to share the using the share file button for file presentation, the converted file seems to be cropped
add the ppt file and the dolby io ui screen shot

ppt which i selected using share button
[ImagesConvertedToPPT (10).pptx](https://github.com/voxeet/voxeet-uxkit-react/files/8964720/ImagesConvertedToPPT.10.pptx)
 
 Dolby io UI 
 
![image](https://user-images.githubusercontent.com/98312418/175233507-6d8e1bfe-81ec-48e3-b34f-05d43830cd9e.png)

any clue on what's going wrong?

**Comment by FabienLavocat** [comment]
@edotappstore have you found what the issue was?

**Comment by edotappstore** [comment]
> @edotappstore have you found what the issue was?

yeah i found the issue .
issue was from my side, the ppt which i had selected in that the images was going out of the slide area so that part was cropped.
ppt link=> [ImagesConvertedToPPT (10).pptx](https://github.com/voxeet/voxeet-uxkit-react/files/8964720/ImagesConvertedToPPT.10.pptx)

sorry for posting as bug

Thank you
