### ISSUE TITLE
Is there a way to show a Thumbnail image if presentation in not active?

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#236]
Hi @FabienLavocat 

Wanted a way to show a default thumbnail images/ loading image while presentation is not active.

![image](https://user-images.githubusercontent.com/98312418/177937541-9f7cf742-72d2-41e2-88f9-e50f5fc1a73d.png)

Current behavior => 1) When no presentation is active the listener can see a black screen with a profile logo along with the name on the dolby ios screen as shown in above image
                                  2)  When we add new presentation file, first the dolby presentation stops showing the above black screen and then restarts with new slide.
                                
Required behavior => can we show a default images/ a thumbnail images, which will be shown to listener when  no presentation is active or in between changing of presentation. 

Thank You

**Comment by FabienLavocat** [comment]
Hey @edotappstore, you could do two things:
- Use an image as avatar for the host of your presentation
- With some CSS, you could override this [line](https://github.com/voxeet/voxeet-uxkit-react/blob/99c0606fc38c86d6f4affbc362b425f18cd967c5/src/styles/components/ConferenceAttendees.less#L716) to use an image of your choice instead.

**Comment by edotappstore** [comment]
> Hey @edotappstore, you could do two things:
> 
> * Use an image as avatar for the host of your presentation
> * With some CSS, you could override this [line](https://github.com/voxeet/voxeet-uxkit-react/blob/99c0606fc38c86d6f4affbc362b425f18cd967c5/src/styles/components/ConferenceAttendees.less#L716) to use an image of your choice instead.

@FabienLavocat  ill try to implement this

thank you
