### ISSUE TITLE
Dolby io gets disconnected after 3 hour

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#241]
Hey There

**Describe the bug**
On going Dolby io conference disconnects after 3 hour. 

**Expected Behaviour**
Conference should be connected until the Admin ends it.

**Steps to Reproduce the Problem**
1) Join Dolby io conference as an admin and Share a PPT
2) Join the same conference as a listener.
3) Wait for 3 hour the conference from Operator side disconnects automatically, so as the listener.

**Specifications**

OS: Windows 
Version: 3.5.1

Is this some kind of timeout?
Is this something default with dolby io?
If yes can we increase the time?

Thank You

**Comment by FabienLavocat** [comment]
Yes, this is a timeout that you can change in your Dolby.io Dashboard. Go to your application, then click on **Communications APIs**, then select the tab **SETTINGS**, then scroll down to **Conferences**. There, you can change the maximum duration of the conference.

<img width="1186" alt="Screen Shot 2022-07-18 at 7 47 35 AM" src="https://user-images.githubusercontent.com/4154532/179538093-94c1bb09-6dc7-416b-bbc5-09afbb9be1d2.png">

**Comment by edotappstore** [comment]
@FabienLavocat Thank you
