### ISSUE TITLE
Logo prop ignored

### ISSUE THREAD

**Issue by jpowell** [voxeet/voxeet-uxkit-react#26]
**Describe the bug**

The logo prop described in the docs has been simply commented out in the `LoadingScreen` component.

**Expected Behaviour**

To be able to pass my logo, I assume it was a string before?

**Comment by jpowell** [comment]
@Energizz we're enjoying vetting the project for online collaboration tool we're building! Do you have an ETA for the release in of the https://github.com/voxeet/voxeet-uxkit-react/tree/release-2.1 branch? 

Also, is the library for the Web SDK repo no longer open source? The Github repo associated with the npm package 404s.

Thanks!

**Comment by Energizz** [comment]
Hello @jpowell sorry for the delay of response, the 2.1.5 released here : https://github.com/voxeet/voxeet-uxkit-react/releases/tag/2.1.5 include a fix for the logo prop

Have a great day,
