### ISSUE TITLE
Question - Is it possible to provide a custom AttendeesSettings component?

### ISSUE THREAD

**Issue by veloware** [voxeet/voxeet-uxkit-react#46]
Is it possible to provide a custom AttendeesSettings Component in order to control video source etc through the Voxeet SDK API? Or at least be able to use a custom component to interact with the Voxeet SDK

**Comment by Energizz** [comment]
Hello @veloware for now it's not possible to give a custom AttendeesSettings component to the ConferenceRoom but maybe in the future we can possibly implement it
