### ISSUE TITLE
ConferenceRoom always prompted to configure audio / video devices

### ISSUE THREAD

**Issue by veloware** [voxeet/voxeet-uxkit-react#53]
**Describe the bug**

Since upgrading to the latest version v2.1.5, I am always prompted before entering the conference room to set up my audio and video devices.  I tried to set the `preConfig` prop to false, however that has no effect.  I see a message in the console - "No audio device configured... forcing preConfig".  I haven't changed anything on my side and never had an issue with an audio device not being configured on start up before.

Reverting to 2.1.2 I do not get the preConfig screen displayed

**Expected Behaviour**

No pre config should display when set to false

**Steps to Reproduce the Problem**

  1. Create a conference as per the docs

**Minimalistic code (recommended)**

[Please provide a link to a repository showing specifically the issue. It should only have the minimal footprint of your own implementation - something which does not requires any NDA.]

**Specifications**

  - Device: [e.g. iPhone6, MacBook Pro, ...]
  - OS: [e.g. iOS8.1, macOS Mojave, ...]
  - Platform: [e.g. Android, iOS, Chrome, ...]
  - Subsystem: [e.g. n.a., CyanogenMod, ...]
  - Version:
    - _for each libraries : name -> version_
    - [e.g. @voxeet/voxeet-sdk 1.8.7]
    - [e.g. @voxeet/react-components 0.31.0]
    - [e.g. node 10.15.0]
    - [...]
  - Hardware:
    - _list of each specific hardware element on the system_
    - [e.g. bluetooth headset]
    - [e.g. camera]
    - [...]

**Comment by jpowell** [comment]
I second this, but it  appears to be only in Chrome. Firefox appears to respect this option.

**Comment by jpowell** [comment]
> I second this, but it appears to be only in Chrome. Firefox appears to respect this option.

Actually - this also shows in Firefox if I have a new session and have never set preferences.

**Comment by FabienLavocat** [comment]
If this issue still happens with the most recent version of the project, please reopen the ticket.
