### ISSUE TITLE
Question - how to use ConferenceRoom as a RTMP stream

### ISSUE THREAD

**Issue by veloware** [voxeet/voxeet-uxkit-react#55]
I see on the Dolby website (https://dolby.io/products/interactivity-apis) it is possible to create a live stream over RTMP + HLS.  Does the ConferenceRoom component support this, and if so, is there any documentation on how to use it?  All that I can see is boolean props for `isWebinar` and `autoHls`?

Thanks

**Comment by veloware** [comment]
@Energizz any idea on the above question? I'm struggling to see how Live streaming fits in with the ConferenceRoom component.  When setting the isWebinar to true, it behaves no different to a normal conference call.

**Comment by jpowell** [comment]
I echo this question. The support team said this is the best option for large group, one to many presenting, and I'd like to know how.

Thanks!

**Comment by veloware** [comment]
@jpowell I haven't had any response from the Dolby team, but if it helps, I have been using Mux for the livestreaming.  To start the live stream you need seem to join a conference as normal, and with the conference id, pass it to the livestream stop endpoint with the payload containing the url for the broadcast provider, im my case, Mux.

```
await axios.post(
        `https://session.voxeet.com/v1/api/conferences/mix/${webinarConferenceId}/live/start`,
        {
          uri: `rtmp://global-live.mux.com:5222/app/${liveStreamPrivateKey}`,
        },
        {
          headers
        },
      );
```

where the liveStreamPrivateKey I got from Mux when creating the RTMP stream.

The issue I had was getting the conference id, but I managed to get it by - 

```
VoxeetSDK.conference.on?.('joined', async () => {
        const conference = await VoxeetSDK.conference;
        const currentConference = await conference.current;
        const conferenceId = await currentConference.id;
        if (conferenceId) {
          setWebinarConferenceId(conferenceId);
        }
```

In regards to the Conference component Dobly has, im still not sure about what `isWebinar` : `true` changes...

Hopefully that helps!

**Comment by jpowell** [comment]
@veloware thank you for your response! Super helpful. We have not hit an instance that the webinar mode doesn't scale for, but we wanted to be prepared nonetheless. I do know that at least in Webinar mode the non-admin users are in listen only mode.

Thanks again! Looks like we're two of only a few using this library...

**Comment by Energizz** [comment]
Hello @jpowell sorry for the delay of response, yes the only way to start a RTMP stream is to start it though the API Call.
If you need more assistance please feel free to reach out our support team.
https://support.dolby.io/ to go thought the support process. 

Have a great day
