### ISSUE TITLE
SDK prop not used

### ISSUE THREAD

**Issue by jpowell** [voxeet/voxeet-uxkit-react#56]
**Describe the bug**

SDK prop ignored.

**Expected Behaviour**

The documentation says that an external instance of the VoxeetSDK can be passed as a prop, but from what I can tell it is never used or passed down to the action components that would use it.

**Comment by Energizz** [comment]
Hello @jpowell sorry for the delay of response, if you still experience some issues, please feel free to reach our customer success team on https://support.dolby.io/

Have a great day

**Comment by FabienLavocat** [comment]
This code was removed.
