### ISSUE TITLE
ConferenceRoom does not close session

### ISSUE THREAD

**Issue by jpowell** [voxeet/voxeet-uxkit-react#57]
**Describe the bug**

ConferenceRoom component does not clean up itself. When the component isn't rendered after any react component change or state transition, the connection to the VTC client is still intact, and other clients can still see / hear the previous session.

**Expected Behaviour**

When the component unmounts, at minimum I'd expect the session to close and the conference to be left.

**Steps to Reproduce the Problem**

  1. Render a conference room
  2. re-render a parent or managing component that doesn't render the conference room
  3. the browser continues to track audio / video with the session open
  4. on page refresh or leave voxeet throws an error

**Minimalistic code (recommended)**

I've had to handle this myself... you can do this with `useEffect` hooks as well, but I'd expect the `ConferenceRoom` component to do this itself.

```typescript
  public async componentDidMount() {
    const sdk = await import('@voxeet/voxeet-web-sdk')
    this.setState({sdk: sdk.default})
  }

  public componentWillUnmount() {
    this.state.sdk.conference.leave()
  }
```

**Comment by Energizz** [comment]
Hello @jpowell sorry for the delay of response, if you still experience some issues, please feel free to reach our customer success team on https://support.dolby.io/

Have a great day

**Comment by xeroxoid** [comment]
This is still an issue and the issue affects the react component UXKit which as per [this documentation](https://dolby.io/developers/interactivity-apis/client-sdk/articles/sdk-support ) is not officially supported.

When the component unmounts there is no handling for correctly leaving the conference, thus the suggested solution by @jpowell should be part of the ConferenceRoom component.
