### ISSUE TITLE
Remove the debug log message

### ISSUE THREAD

**Issue by jfan-dolby** [voxeet/voxeet-uxkit-react#6]
**Describe the bug**

`console.log("Quality indicators:", indicators)`

This piece of code gets invoked periodically and keeps on printing logs in the dev console, it should be removed.
https://github.com/voxeet/voxeet-uxkit-react/blob/master/src/app/actions/ConferenceActions.js#L1226

**Comment by Energizz** [comment]
The log has been removed, it will be deployed in the next release
