### ISSUE TITLE
Audio output device selector has stopped appearing in Safari & Firefox

### ISSUE THREAD

**Issue by hablodoug** [voxeet/voxeet-uxkit-react#76]
**Describe the bug**

Conference settings audio output device selector doesn't show on Safari, even if you have more than one device (I have 3 on one comp, 1 on macbook, both same issue)

**Expected Behaviour**

Should see output device selector when pressing 'Settings' in default UX kit.

**Steps to Reproduce the Problem**

  1. Go to... https://dolby.io/dashboard on Safari v13.1.2
  2. Click... interactivitiy APIs > TEST
  3. See the... UX kit not show the option to choose any output device. 

or use UX kit with basic <ConferenceRoom /> component 

**Minimalistic code (recommended)**

<ConferenceRoom
          attendeesWaiting={AttendeesWaiting}
          loadingScreen={LoadingScreen}
          isWidget={false}
          dolbyVoice={true}
          autoJoin
          videoRatio={videoRatio}
          handleOnLeave={handleOnLeave}
          handleOnConnect={() => {}}
          constraints={constraints}
          consumerKey={settings.consumerKey}
          consumerSecret={settings.consumerSecret}
          conferenceAlias={callId}
          videoCodec={'H264'}
          sdk={voxeet.instance}
          displayModes={['tiles']}
          userInfo={userInfo}
        />

**Specifications**

  - Device: macbook pro, and macintosh
  - OS: both Catalina and BigSur produce same result
  - Platform: mac 
  - Subsystem: [e.g. n.a., CyanogenMod, ...]
  - Version:
    "@voxeet/react-components": "^3.0.0",
    "@voxeet/voxeet-web-sdk": "^3.0.0",
  - Hardware:
    1x macbook pro with no external devices. 1x macintosh with usb webcam + 2 audio output devices

**Comment by hablodoug** [comment]
It's the same on Firefox

![image](https://user-images.githubusercontent.com/66522737/99713872-c1d29400-2a9c-11eb-9386-e482dc5497ea.png)

**Comment by dwecci** [comment]
@hablodoug Firefox and Safari don't enumerate output devices so there is no use of output device selector
Please try webrtc example here:
https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by hablodoug** [comment]
yep looks like a web-rtc issue :(
