### ISSUE TITLE
Documented npm installation fails

### ISSUE THREAD

**Issue by hectoroso** [voxeet/voxeet-uxkit-react#80]
**Describe the bug**

The Readme instructs to use the following command to install this package via `npm`:

`npm i @voxeet/voxeet-web-sdk @voxeet/react-components @voxeet/react-redux-5.1.1@5.1.1 --save`

The result is:
```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@voxeet/react-components" under a package
npm ERR! also called "@voxeet/react-components". Did you name your project the same
npm ERR! as the dependency you're installing?
```

Using `yarn` works successfully, though there is this warning:
```
warning " > @voxeet/react-components@3.0.0" has incorrect peer dependency "@voxeet/voxeet-web-sdk@2.3.0".
```

**Expected Behaviour**

Packages are correctly installed.

**Steps to Reproduce the Problem**

  1. git clone https://github.com/voxeet/voxeet-uxkit-react.git
  2. cd voxeet-uxkit-react
  3. npm i @voxeet/voxeet-web-sdk @voxeet/react-components @voxeet/react-redux-5.1.1@5.1.1 --save

**Specifications**

  - Device: MacBook Pro
  - OS: MacOs 10.15.7

**Comment by Energizz** [comment]
Hello,

Thanks for report. You should change the name of the project inside the `package.json` and it should be fine. (Same name on package.json and @voxeet/react-components installed using npm i). It's a mistake inside the readme.

Have a great day,
